#!/bin/tcsh -f

# CMSC 216, Fall 2019, Project #11
# Public test 3 (public03)
#
# Runs xargs.x in default mode, with no explicit target program (so
# /bin/echo will be used), with its standard input coming from the output of
# the "ls" command.  "ls" is being used to list (i.e., print to its standard
# output) the contents of a directory that contains several files (the
# directory is in the project tarfile).  The names of the files in the
# directory will all be joined and echoed on the same output line (which is
# the effect of standard mode).
#
# (c) Larry Herman, 2019.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

ls public03+08.directory | ./xargs.x
