#!/bin/tcsh -f

# CMSC 216, Fall 2019, Project #11
# Public test 1 (public01)
#
# Runs xargs.x in default mode, with no explicit target program (so
# /bin/echo will be used), with one line of data in its standard input.
#
# (c) Larry Herman, 2019.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

./xargs.x < public01.input
