#!/bin/tcsh -f

# CMSC 216, Fall 2019, Project #13
# Public test 4 (public4)
#
# Tests the program with two filenames on the command line, so two threads will
# be created.
#
# (c) Amulya Bellam and Larry Herman, 2019.  You are allowed to use this
# code yourself, but not to provide it to anyone else.

./wc-threaded.x public4.inputdata1 public4.inputdata2
