#!/bin/tcsh -f

# CMSC 216, Fall 2019, Project #13
# Public test 3 (public3)
#
# Tests the program with just one filename on the command line, meaning only
# one thread will be created (besides the main thread).  The file exists but
# is an empty file, so it should have zero lines, works and characters.
#
# (c) Amulya Bellam and Larry Herman, 2019.  You are allowed to use this
# code yourself, but not to provide it to anyone else.

./wc-threaded.x public3.inputdata
