#!/bin/tcsh

# CMSC 216, Fall 2019, Project #12
# Public test 5 (public05)
#
# Tests the second program in counting the number of digits in a negative
# number where it appears more than once.
#
# (c) Rana Khalil and Larry Herman, 2019.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

module load spim

spim -file prog2.s < public05.input | tail -n +2
