#!/bin/tcsh

# CMSC 216, Fall 2019, Project #12
# Public test 10 (public10)
#
# Tests the third program in counting the number of digits in a number that
# does not contain the digit.
#
# (c) Rana Khalil and Larry Herman, 2019.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

module load spim

spim -file prog3.s < public10.input | tail -n +2
