#!/bin/tcsh

# CMSC 216, Fall 2019, Project #12
# Public test 1 (public01)
#
# Tests the first program on an example input.
#
# (c) Rana Khalil and Larry Herman, 2019.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

module load spim

spim -file prog1.s < public01.input | tail -n +2
