#!/bin/tcsh

# CMSC 216, Fall 2019, Project #12
# Public test 2 (public02)
#
# Tests the first program in computing the sum of the first zero cubes (zero
# terms, so zero should be printed).
#
# (c) Rana Khalil and Larry Herman, 2019.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

module load spim

spim -file prog1.s < public02.input | tail -n +2
